server:
  port: 8084
spring:
  application:
    name: eureka-security-server
  security:
    user:
      name: jay
      password: 123456
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false